version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - GLADIA_API_KEY=${GLADIA_API_KEY}
    volumes:
      - uploads:/app/uploads
      - logs:/var/log/ainterview
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - uploads:/app/uploads
    depends_on:
      - web
    restart: unless-stopped

volumes:
  uploads:
  logs: 